### ISSUE TITLE
Clickable Property

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#126]
Seems like in builder if Clickable is added, the object becomes clickable.  However if that property is set to false the object still seems clickable until deleted.

**Comment by anthonyrowe** [comment]
Edward, I think you fixed this already?  Wasn't just a builder problem, but an overall clickable issue

**Comment by EdwardLu2018** [comment]
Hm, I did not explicitly fix this. If it works, I think it was fixed by something else. Probably when Ivan (or Mike?) added a way to unset attributes my making them null?

**Comment by EdwardLu2018** [comment]
Fixed by setting click_listener to null.
