### ISSUE TITLE
Startup Landmarks

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#138]
Would be great to have a specific landmark or a set of landmarks (perhaps randomly selected if more than 1) where people appear in the scene.  It could have a static name or be defined similar to how we manage screenshare in scene config.  (sorry if this is a repeat)

**Comment by mwfarb** [comment]
We have added this to scenes before and it's really useful. Do we have a document published anywhere that shows how to do this? 

I could start gathering lists of techniques like this for our docs site.

**Comment by hiliang-cmu** [comment]
There is sort of overlap now with `startPosition#` entities, it currently selects one at random. However, starting positions are not listed as landmarks

Perhaps if we refactor `startPosition` into a component-system, then we could attach it to landmarks as well?

**Comment by hiliang-cmu** [comment]
And also maybe add random radius

**Comment by nampereira** [comment]
Yeah, refactor it into a component-system is a good idea.

**Comment by hiliang-cmu** [comment]
This is now WIP via #276
