### ISSUE TITLE
nginx redirects some scenes unexpectedly

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#183]
It seems to be able to not resolve proxies in some cases:
- https://arena-dev1.conix.io/public/arts redirects to https://arena-dev1.conix.io/arts
- https://arena-dev1.conix.io/public/build redirects ti https://arena-dev1.conix.io/build
- There may be others.

**Comment by hiliang-cmu** [comment]
I'm not sure there's a way around this, because `arts` and `build` directories really do exist, and will always take priority in the attempt to "resolve" the path.

**Comment by hiliang-cmu** [comment]
Closing this issue as won't fix.

There *is* the possible measure to reduce the surface of "served" scene and namespace names by consolidating our real-directory/files, for example by putting `arts` and `build` underneath `tools` directory.
