### ISSUE TITLE
Improve errors on scene load

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#190]
For example, when a user is unauthorized, display better message of the error.

**Comment by mwfarb** [comment]
Where you thinking of wording, or sweet alert vs. js alert?

**Comment by nampereira** [comment]
Was thinking of wording. Believe right now we don't give details about the error. Using sweet alert is not a bad idea also.

**Comment by mwfarb** [comment]
Persist returned a valid body as 'json' and error message as 'text'. This made json response handlers nullify the error messages.
- Persist return error as json: https://github.com/conix-center/arena-persist/commit/cdfaf13d770738a08895a694aed4baa3828af12a
- Persist increase read/write granularity of mqtt permission errors: https://github.com/conix-center/arena-persist/commit/41fccf71be068082da73e181086c1f1335ebff41
- Prefer sweetalert over alert: https://github.com/conix-center/ARENA-core/pull/210
