### ISSUE TITLE
Build: Better object type handling

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#191]
Currently, it is a bit confusing to have several types (where object type appears twice). Maybe extract data section of objects into separate json definitions.

**Comment by hiliang-cmu** [comment]
Perhaps slightly different semantics, because the `type` prop on top level is supposed to be indicative of the message type, whereas the `data` payload contains the actual `object_type` mostly commonly used.

**Comment by nampereira** [comment]
Ah, I meant that 3D object type appears twice, but yeah, there should be a better way of showing this.
![image](https://user-images.githubusercontent.com/3504501/108128339-94d15580-707a-11eb-859e-2a9994f62a9b.png)
