### ISSUE TITLE
Camera Location Readout

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#213]
Would be super cool if you could bring up either a live output overlay or perhaps a static update in the settings tab that showed your current camera location and orientation.  Nice for gauging where to place models / test audio ranges etc

**Comment by mwfarb** [comment]
Related to #198, showing where other users are, direction, audio range circle.

**Comment by mwfarb** [comment]
@johnchoi313 @hiliang-cmu
