### ISSUE TITLE
Directional Light Rotation Field does not seem to do anything?

### ISSUE THREAD

**Issue by johnchoi313** [conix-center/ARENA-core#222]
Tried setting directional light object on ARENA editor.

Tried applying rotation property to directional light.

Set Rotation property to both quaternion and euler value for x,y,z,w.

Directional light rotation  does not appear to change.

(This is evident when viewing the real-time shadow rendering angles.)

**Comment by nampereira** [comment]
Closing. Directional lights seem to work as expected. Checkout https://aframe.io/docs/1.2.0/components/light.html#sidebar
