### ISSUE TITLE
Update menu bar

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#249]
Update the arena link in the black menu bar to the landing page; Add a "Scenes" link too.

**Comment by mwfarb** [comment]
Added to:
- https://github.com/conix-center/ARENA-core/commit/970a6f0f90e3cb8a5d47ad6021cdc1db6d7cc386
- https://github.com/conix-center/arena-account/commit/bca3d41338ee7854b9d9baa3e15b6e463a2aa9f5
- https://github.com/conix-center/arts/commit/acdc6d52e789c2105d1c7d7546239a8c0ba8c3ad
