### ISSUE TITLE
Privacy settings 

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#26]
If cookies are disabled, we show icons on a blank screen with no error messages. Pretty bad feedback.

The Paho MQTT js library requires `LocalStorage` and without it we crash hard. We can show a message to the user that cookies are disabled, and that the ARENA requires them to be enabled to function.

https://github.com/eclipse/paho.mqtt.javascript/wiki/LocalStorage-Restrictions

**Comment by mwfarb** [comment]
Perhaps low-occurrence, but one we should handle.

**Comment by nampereira** [comment]
Agree. I have been using localstorage without even thinking too much about that kind of issue, if localstorage is missing it is definitely going to break things. We should just detect and warn the user.
