### ISSUE TITLE
Hardcoded transparent bondary boxes seem to still be around?

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#289]
Unless I'm crazy, I think those transparent border boxes hard-coded in the HTML are still floating around scenes causing artifacts.  You can see them in the sky-island scene / inspector.

**Comment by mwfarb** [comment]
I can't remember where we landed on this. I think the suggestion was to move their creation in the scene to either scene-options. There may have been a camp that also suggested to remove them altogether and create a docs page describing how to recreate? Does anyone remember?

**Comment by anthonyrowe** [comment]
I don't think they server any purpose and constantly get in the way.  Can't we just delete them?  If someone wants bounding boxes for physics (whatever that looks like) they can just add them.  This really shouldn't be a special feature or in scene config or anything

**Comment by mwfarb** [comment]
Yep, I'll do that.

**Comment by mwfarb** [comment]
Fixed in c8a872b
