### ISSUE TITLE
Quick AR Mode

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#294]
We could use a set of URL params that allow AR users to drop into a scene without audio, video, perhaps location and as anonymous.  The use-case would be public QR codes in the wild embedded in April tags that quickly let normal browser users interact with AR content.  Read-only is probably the way to go, although we might want them to be able to click on application buttons?  Maybe this should be broken out into a few URL params or even scene config options to let the design select.

**Comment by hiliang-cmu** [comment]
Should the (tentative) `enterar` flag imply anything with video? There is a `noav` option already, is jitsi and AR exclusive? Mostly having to do with when in the load process to force the Enter-AR function

**Comment by hiliang-cmu** [comment]
For first version of this, will be skipping jitsi, and loading immediately after persist assets load.

Pending issues to resolve include a means to enable jitsi video by a new **popup** for simple Yes/No enable *prior* to loading the scene.

**Comment by hiliang-cmu** [comment]
Ono it added every rebased commit

**Comment by hiliang-cmu** [comment]
Note: the generic solution is based on the WebXR standard's behavior that `requestSession()` for immersive-mode MUST be from a user-initiated event (e.g. click button).
