### ISSUE TITLE
Add a custom head model URL to the scene options

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#391]
**Is your feature request related to a problem? Please describe.**
We would like to let scene owners to set a head model for everyone visiting the scene.

**Describe the solution you'd like**
Add a field in the scene options.
We also need to write down the requirements to create a head model (the right size and rotation need to be set in the GLTF).

**Comment by mwfarb** [comment]
Added in https://github.com/conix-center/ARENA-core/pull/425

**Comment by mwfarb** [comment]
Defined by "scene-options": { "sceneHeadModel": "/store/models/Head.gltf" } for example.
