### ISSUE TITLE
Anonymous Login still not quite right

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#405]
When you login as anonymous, you can see the public scenes now, but none of the buttons are active and the scene URL doesn't update when you select scenes.  As a side note, maybe we should have public/lobby selected by default?  Hopefully it will be obvious what button to enter a scene, but a friend said they looked at ARENA last week and "couldn't figure out how to get it to do anything".

**Comment by mwfarb** [comment]
Related #383

**Comment by hiliang-cmu** [comment]
Yeah, dupe #383
