### ISSUE TITLE
Propagate settings change

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#48]
Currently, name changes are not propagated to chat. Chat keeps a copy of the name that is only initialized when it is created. We could dispatch a "settings change" event with the new settings, so that interested parts of the code could listen to it and update their stuff ?

The event could look like:
`const event = new CustomEvent('newsettings', { name: 'new name', 'other-setting': 'new-value', ... });`

**Comment by mwfarb** [comment]
This makes sense, even after chat setup, changes may happen in real-time. Wouldn't it have to also propagate to MQTT somehow for others' chat lists? I'm sending name updates to the jitsi heartbeat messages now, but maybe we need to think of a central way to combine these things.

Like, heartbeat messages can fire an event for chat and other systems to listen to.

But, we still may have the issue of out of sync state on first connection?

**Comment by nampereira** [comment]
The chat does not use the user name on mqtt, uses a user id it randomly creates. The chat does heartbeats too to maintain the user list up-to-date. We should definitely look at combining these, if possible.

**Comment by mwfarb** [comment]
Propagation of name added in #59,  ready to used in #56.
