### ISSUE TITLE
Auth integration:

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#53]
- [x] Browser flow
- [x] Command-line flow
- [x] Broker auth

**Comment by mwfarb** [comment]
#18 adds part 1, browser flow.

**Comment by mwfarb** [comment]
Part 2 completed in https://github.com/conix-center/ARENA-py/pull/40.
Part 3 completed in https://github.com/conix-center/arena-services-docker/commit/72df009b736e892ee86a0f415fdf10cf8464dd83
