### ISSUE TITLE
How to rotate the camera.

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#54]
This would be useful for the find user (chat functionality), and possibly other stuff.

The chat is doing this to move the camera to be in front of another user:
https://github.com/conix-center/ARENA-core/blob/d6e8536216b307a15dbc90de77a93fdc055591f5/mqtt-chat/mqtt-chat.js#L433

**Comment by mwfarb** [comment]
Resolved in https://github.com/conix-center/ARENA-core/commit/5c3c4cc7cd9abc7f9db2409fcf766d6ba0eec355.
