### ISSUE TITLE
Use different mqtt instances

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#62]
We have three bridged mosquitto instances at arena.andrew.cmu.edu that can be accessed through web sockets:

- wss://arena.andrew.cmu.edu/mqtt/
- wss://arena.andrew.cmu.edu/mqtt1/
- wss://arena.andrew.cmu.edu/mqtt2/

A simple load-balancing mechanism can be implemented by having the clients connect to these randomly.

**Comment by hiliang-cmu** [comment]
This type of round-robin behavior might be better done at DNS level.

My thinking i sthat each destination would need the WSS proxy in front, but as far load balancing goes, the above machine/network/nginx-process would be chokepoint for all 3 destinations

**Comment by nampereira** [comment]
Let's see what the monitoring tells us. Nginx should be able to handle quite a few connections, i hope. Main reason for this is because each mosquitto instance is a single thread. This should allow using a little more of the cpu.

**Comment by hiliang-cmu** [comment]
Ah, that makes sense if the concern is mosquito process itself. 

In that case an nginx-level such as this for the reverse proxy would remove the need to implement anything client-side: https://nginx.org/en/docs/http/load_balancing.html

**Comment by nampereira** [comment]
Yeah, you sure this works for our setup ? I though clients need to hit the same server always..

**Comment by nampereira** [comment]
More like this: https://www.nginx.com/blog/nginx-plus-iot-load-balancing-mqtt/

**Comment by nampereira** [comment]
Reopened; Actually, changing to what Ivan suggested would possibly work better/be simpler: https://nginx.org/en/docs/http/load_balancing.html
