### ISSUE TITLE
aframe-spe-particles-component disabled

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#74]
- Examples using flames/smoke/sparks no longer work
- Perhaps after recent A-Frame upgrade?
- https://xr.andrew.cmu.edu/x/refactor/?scene=render

**Comment by EdwardLu2018** [comment]
should be fixed in 0ab02d73ce6eadda015f68e9ee646946efd76c59

check out the burning avocado in: https://xr.andrew.cmu.edu/x/dev/?scene=render
