### ISSUE TITLE
Find and add to scenes some iconic buildings of CONIX schools

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#75]
For example: https://3dwarehouse.sketchup.com/model/8c8d3556489d78b47f6d80d33c9f19eb/Sather-Tower-Campanile-UC-Berkeley

Getting from SketchUp to GLTF was a bit of an adventure:
The online converters are a lie and don’t generate valid GLTFs
The SketchUp GLTF export plugin was written for SketchUp 2016 and seems to hang SketchUp 2020 — these models were created in SketchUp 2017, so the 2016 version refuses to open them
The only thing I found that worked was installing Adobe Dimension, opening the SketchUp file there, and exporting it
Dimension doesn’t seem to edit these models well, so if you want to patch up some textures, I recommend doing that in SketchUp first, then saving a copy, using Dimension to convert to GLTF, and you’re off to the races

**Comment by mwfarb** [comment]
Added this advice to docs site: https://github.com/conix-center/ARENA/commit/e630049f6e6fb47c8fd3c4e673fef7f884202cc4

**Comment by mwfarb** [comment]
Closed, thanks to @CourtKowaluk and @nampereira.
