### ISSUE TITLE
Add client-side TTL

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#78]
- Add browser TTL for objects.
- This would allow `persist=false` objects to be removed from each client via client side process.
- Question? Does this mean each client should manipulate a-frame delete locally and not fire O(n) delete mqtt messages?
- Question? Should `persist=true` TTL objects appear in DB for their duration?

**Comment by hiliang-cmu** [comment]
> Question? Does this mean each client should manipulate a-frame delete locally 
For web clients this seems easy enough. Any other clients will need to emulate this `expiresAt` behavior for their entity management
> and not fire O(n) delete mqtt messages?
Probably not. Persist doing it solely (as it does now) at least is more manageable 
> Question? Should persist=true TTL objects appear in DB for their duration? 
This is current behavior and works fine, as mongodb backend supports `expiresAt` behavior. What I wish were possible, is to have a db trigger event on deletion result in the MQTT message. Unfortunately this is not practically doable in any stretch of a mongodb "trigger".
